### ISSUE TITLE
Exception when try to start windows-server box

### ISSUE THREAD

**Issue by gprossliner** [gusztavvargadr/packer#124]
Hi!

I want to setup a dev envionrment using a Windows Server for Active Directory.
I tries the most basic setup:

* Installed VirtualBox (apt)
* Installed Vagrant (apt)
* Installed ansible (should not be used in this)

```bash
$ VBoxManage --version
5.2.18_Ubuntur123745
$ vagrant --version
Vagrant 2.0.2
```

They I wanna test windows-server image by using most prmitive Vagratfile:
```ruby
Vagrant.configure("2") do |config|
  
  config.vm.define "dc" do |dcconf|
    dcconf.vm.box = "gusztavvargadr/windows-server"
  end
end
```
After executing ```vagrant up```, I get the following log-output:

```
Bringing machine 'swarm-node3' up with 'virtualbox' provider...
==> dc: Box 'gusztavvargadr/windows-server' could not be found. Attempting to find and install...
    dc: Box Provider: virtualbox
    dc: Box Version: >= 0
==> dc: Loading metadata for box 'gusztavvargadr/windows-server'
    dc: URL: https://vagrantcloud.com/gusztavvargadr/windows-server
==> dc: Adding box 'gusztavvargadr/windows-server' (v1809.0.1901) for provider: virtualbox
    dc: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/windows-server/versions/1809.0.1901/providers/virtualbox.box
==> dc: Successfully added box 'gusztavvargadr/windows-server' (v1809.0.1901) for 'virtualbox'!
#<Thread:0x000056274111f5a8@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        36: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
        35: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
        34: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
        33: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
        32: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
        31: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
        30: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        29: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        28: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        27: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        26: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:48:in `call'
        14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `machine'
        13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `new'
        12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:140:in `initialize'
        11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:248:in `communicate'
        10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/registry.rb:27:in `get'
         9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
         8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
         5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
         4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
         3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
         2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- winrm (LoadError)
Traceback (most recent call last):
        36: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
        35: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
        34: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
        33: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
        32: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
        31: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
        30: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        29: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        28: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        27: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        26: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:48:in `call'
        14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `machine'
        13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `new'
        12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:140:in `initialize'
        11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:248:in `communicate'
        10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/registry.rb:27:in `get'
         9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
         8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
         5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
         4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
         3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
         2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- winrm (LoadError)
```

Is this a known behaviour, I am I doing something wrong?
Thank you

**Comment by gusztavvargadr** [comment]
@gprossliner seems to be an issue with Vagrant and `winrm` itself. Do you have any Vagrant plugins installed? I think with Vagrant 2+ the `winrm` plugins are not needed anymore and should be removed.

Also, can you try with the latest Vagrant version? That one seems to be quite outdated. https://www.vagrantup.com/downloads.html

**Comment by gprossliner** [comment]
Hello!

Previouly I installed vagrant with apt, which installed 2.0:

```bash
$ apt search vagrant
...
vagrant/bionic,bionic,now 2.0.2+dfsg-2ubuntu8 all [installed]
```
Now I've checked the **Beware of system package managers!** within your docs.
So I install by yum, using https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.rpm directly
...
$ vagrant --version
Vagrant 2.2.4
```

I retried my test, with results:
```bash
Bringing machine 'dc' up with 'virtualbox' provider...
==> dc: Importing base box 'gusztavvargadr/windows-server'...
==> dc: Matching MAC address for NAT networking...
==> dc: Checking if box 'gusztavvargadr/windows-server' version '1809.0.1901' is up to date...
==> dc: Setting the name of the VM: docker-swarm-setup_dc_1553596749587_92753
==> dc: Fixed port collision for 22 => 2222. Now on port 2202.
==> dc: Vagrant has detected a configuration issue which exposes a
==> dc: vulnerability with the installed version of VirtualBox. The
==> dc: current guest is configured to use an E1000 NIC type for a
==> dc: network adapter which is vulnerable in this version of VirtualBox.
==> dc: Ensure the guest is trusted to use this configuration or update
==> dc: the NIC type using one of the methods below:
==> dc: 
==> dc:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> dc:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> dc: Clearing any previously set network interfaces...
==> dc: Preparing network interfaces based on configuration...
    dc: Adapter 1: nat
==> dc: Forwarding ports...
    dc: 3389 (guest) => 33389 (host) (adapter 1)
    dc: 5985 (guest) => 55985 (host) (adapter 1)
    dc: 5986 (guest) => 55986 (host) (adapter 1)
    dc: 22 (guest) => 2202 (host) (adapter 1)
==> dc: Running 'pre-boot' VM customizations...
==> dc: Booting VM...
==> dc: Waiting for machine to boot. This may take a few minutes...
    dc: WinRM address: 127.0.0.1:55985
    dc: WinRM username: vagrant
    dc: WinRM execution_time_limit: PT2H
    dc: WinRM transport: negotiate
==> dc: Machine booted and ready!
==> dc: Checking for guest additions in VM...
==> dc: Mounting shared folders...
    dc: /vagrant => /home/guenter.prossliner@world-direct.at/proj/docker-swarm-setup
```

Test:
````
$ vagrant ssh dc
vagrant@127.0.0.1's password: <entered 'vagrant'>
vagrant@WIN-K08K2QM5JGA C:\Users\vagrant> 
````

So everything seems fine with 2.2.4.
No I will try vagrant rdp cd, and vagrant powershell provisioning

Thank you for you help

**Comment by gusztavvargadr** [comment]
@gprossliner sweet, glad to hear it works :) Please reopen / create a new issue if you notice anything else.
